---
title: "Week 5 Assignment - Tidying and Transforming Data"
author: "Kalyanaraman Parthasarathy"
output:
  html_document:
    code_folding: show
    depth: 4
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---


## Load required packages

```{r}
knitr::opts_chunk$set(echo = TRUE)

# Clear the console
cat("\014")

# Check if the package is installed. If not, install the package
if(!require('tidyr')) {
  install.packages('tidyr')
  library(tidyr)
}

# Check if the package is installed. If not, install the package
if(!require('dplyr')) {
  install.packages('dplyr')
  library(tidyr)
}

```

## Question 1

```{r}
# 1. Create a .CSV file (or optionally, a MySQL database!) that includes all of the information above

flightDataCSV <- read.csv("https://raw.githubusercontent.com/kalyanparthasarathy/DATA607/master/week5-flights-data.csv")
flightDataCSV

```

## Question 2


```{r}
# 2. Read the information from your .CSV file into R,and use tidyr and dplyr as needed to tidy and transform your data

# Transform the columns of cities data into rows
tidyData <- gather(flightDataCSV, "City","# of Flights", 3:7)
tidyData

# Transpose flight status to columns - delayed and on time
tidyDataNew <- spread(tidyData, Status, `# of Flights`)

tidyDataNew

```

## Question 3


```{r}
# 3. Perform analysis to compare the arrival delays for the two airlines

# Delayed percentage of total flights by city
delayedByCity <- mutate(tidyDataNew, delay_percent=round(delayed/(delayed + `on time`) * 100, 2))

delayedByCity

# On time percentage of total flights by city
ontimeByCity <- mutate(tidyDataNew, ontime_percent=round(`on time`/(delayed + `on time`) * 100, 2))

ontimeByCity

# Delayed percentage of total flights by Airlines
(airlinesOverallStats <- group_by(tidyDataNew, Airlines))
airlinesOverallStats <- select(airlinesOverallStats, Airlines, delayed, 'on time')
airlinesOverallStatsSummary <- summarise(
                          airlinesOverallStats
                          , total_delayed=sum(delayed)
                          , total_ontime=sum(`on time`)
                          , delay_percent=round(sum(delayed)/(sum(delayed) + sum(`on time`)) * 100, 2)
                          , ontime_percent=round(sum(`on time`)/(sum(delayed) + sum(`on time`)) * 100, 2)
                        )
airlinesOverallStatsSummary

```

Overall, AM West airlines has performed better than ALASKA airlines with respect to on time performance.

